package com.example.edamamnutrition.UserDatabase


import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey
import java.io.Serializable

//ENTITY OF THE USER THAT IS STORED IN THE DATABASE USING THE ROOM FRAMEWORK
//Page 2 : Paragraph 4
@Entity(tableName = "user_table")
data class User(
    //SETTING AN AUTOGENERATED PRIMARY KEY, THIS MAY BE REDUNDANT AS WE FORCE THE PRIMARY KEY WHEN WE CREATE THE USER
    @PrimaryKey(autoGenerate = true)
    val id: Int?,
    @ColumnInfo(name = "calories")
    var calories: Int,
    @ColumnInfo(name = "maxSearch")
    var maxSearch: Int,
    @ColumnInfo(name = "diet")
    var diet: String,
    @ColumnInfo(name = "priority")
    var priority: String
    )