package com.example.edamamnutrition.JSONModels

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey
import java.lang.reflect.Constructor

//THIS IS THE PRIMARY DATA CLASS WE WORK WITH IN THE MAIN ACTIVITY, THE VALUES FROM THE ROOT OBJECT
//ARE PARSED INTO THIS OBJECT
data class Recipe(
    var label: String,
    var image: String,
    var url: String,
    var calories: Float,
    var dietLabels: List<String>?,
    var dishType: List<String>?,
    )
{
    //THIS WAS THE CONSTRUCTOR GENERATED BY "kotlin data class from JSON" WE DID HOWEVER NOT NEED ALL OF THESE VALUES
    /*constructor(
        calories: Float,
        cautions: List<String>,
        co2EmissionsClass: String,
        cuisineType: List<String>,
        dietLabels: List<String>,
        digest: List<Digest>,
        dishType: List<String>,
        externalId: String,
        glycemicIndex: Int,
        healthLabels: List<String>,
        image: String,
        images: Images,
        ingredientLines: List<String>,
        ingredients: List<Ingredient>,
        instructions: List<String>,
        label: String,
        mealType: List<String>,
        shareAs: String,
        source: String,
        tags: List<String>,
        totalCO2Emissions: Int,
        totalDaily: TotalDaily,
        totalNutrients: TotalNutrients,
        totalWeight: Float,
        uri: String,
        url: String,
        yield: Int
    ): this(label, image, url)*/


}